<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songlist [
  <!ELEMENT songlist (song, (song|another_song)*)>
  <!ELEMENT song (artist, title, genre, bpm, modes)>
  <!ELEMENT artist (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT genre (#PCDATA)>
  <!ELEMENT bpm (#PCDATA)>
  <!ELEMENT modes (single, double)>
  <!ELEMENT single (normal?, hyper?, another?)>
  <!ELEMENT double (normal?, hyper?, another?)>
  <!ELEMENT normal (diff, notes)>
  <!ELEMENT hyper (diff, notes)>
  <!ELEMENT another (diff, notes)>
  <!ELEMENT diff (#PCDATA)>
  <!ELEMENT notes (#PCDATA)>
  <!ATTLIST song id ID #REQUIRED>
  <!ATTLIST song age (old|new) "new">
  <!ATTLIST song another_id IDREF #IMPLIED>
  <!ELEMENT another_song (artist, title, genre, bpm, modes)>
  <!ATTLIST another_song id ID #REQUIRED>
  <!ATTLIST another_song age (old|new) "new">
  <!ATTLIST another_song original_id IDREF #REQUIRED>
]>
<songlist>
<song id="N13001">
  <artist>ＴЁЯＲＡ</artist>
  <title>ALFARSHEAR 双神威に廻る夢</title>
  <genre>HYPER J-POP SEVEN</genre>
  <bpm>170</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>548</notes></normal>
      <hyper><diff>7</diff><notes>838</notes></hyper>
      <another><diff>10</diff><notes>1049</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>548</notes></normal>
      <hyper><diff>9</diff><notes>838</notes></hyper>
      <another><diff>10</diff><notes>1043</notes></another>
    </double>
  </modes>
</song>
<song id="N13002">
  <artist>Zektbach</artist>
  <title>Apocalypse ～dirge of swans～</title>
  <genre>ORATORIO</genre>
  <bpm>170</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>510</notes></normal>
      <hyper><diff>9</diff><notes>921</notes></hyper>
      <another><diff>10</diff><notes>1214</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>480</notes></normal>
      <hyper><diff>9</diff><notes>981</notes></hyper>
      <another><diff>11</diff><notes>1270</notes></another>
    </double>
  </modes>
</song>
<song id="N13003">
  <artist>teranoid &amp; MC Natsack</artist>
  <title>ay carumba!!!!</title>
  <genre>NUSTYLE GABBA</genre>
  <bpm>180</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>520</notes></normal>
      <hyper><diff>9</diff><notes>805</notes></hyper>
      <another><diff>10</diff><notes>975</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>520</notes></normal>
      <hyper><diff>10</diff><notes>820</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13004">
  <artist>S.S.D.FANTASICA feat. Naomi Koizumi</artist>
  <title>BALLAD THE FEATHERS</title>
  <genre>CELTIC REEL</genre>
  <bpm>132</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>367</notes></normal>
      <hyper><diff>6</diff><notes>554</notes></hyper>
      <another><diff>8</diff><notes>64</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>357</notes></normal>
      <hyper><diff>7</diff><notes>560</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13005">
  <artist>DJ YOSHITAKA</artist>
  <title>Bloody Tears (IIDX EDITION)</title>
  <genre>HARD RENAISSANCE</genre>
  <bpm>170</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>574</notes></normal>
      <hyper><diff>9</diff><notes>1012</notes></hyper>
      <another><diff>10</diff><notes>1094</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>574</notes></normal>
      <hyper><diff>10</diff><notes>1009</notes></hyper>
      <another><diff>11</diff><notes>1280</notes></another>
    </double>
  </modes>
</song>
<song id="N13006">
  <artist>小野秀幸</artist>
  <title>bluemoon</title>
  <genre>LATIN HORNS GROOVE</genre>
  <bpm>140</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>292</notes></normal>
      <hyper><diff>7</diff><notes>867</notes></hyper>
      <another><diff>10</diff><notes>1174</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>473</notes></normal>
      <hyper><diff>10</diff><notes>961</notes></hyper>
      <another><diff>11</diff><notes>1207</notes></another>
    </double>
  </modes>
</song>
<song id="N13007">
  <artist>Y&amp;Co.</artist>
  <title>BOOM BOOM DISCO NIGHT</title>
  <genre>EUROBEAT</genre>
  <bpm>155</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>520</notes></normal>
      <hyper><diff>8</diff><notes>938</notes></hyper>
      <another><diff>10</diff><notes>1151</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>520</notes></normal>
      <hyper><diff>9</diff><notes>927</notes></hyper>
      <another><diff>10</diff><notes>1148</notes></another>
    </double>
  </modes>
</song>
<song id="N13008">
  <artist>Remixed by Orange Lounge</artist>
  <title>BREAK OUT</title>
  <genre>LOUNGE HOUSE</genre>
  <bpm>129</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>352</notes></normal>
      <hyper><diff>7</diff><notes>642</notes></hyper>
      <another><diff>9</diff><notes>888</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>352</notes></normal>
      <hyper><diff>7</diff><notes>641</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13009">
  <artist>SADA</artist>
  <title>Broadbanded</title>
  <genre>TRANCE</genre>
  <bpm>140</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>454</notes></normal>
      <hyper><diff>8</diff><notes>726</notes></hyper>
      <another><diff>11</diff><notes>1019</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>436</notes></normal>
      <hyper><diff>10</diff><notes>727</notes></hyper>
      <another><diff>11</diff><notes>899</notes></another>
    </double>
  </modes>
</song>
<song id="N13010">
  <artist>佐々木博史</artist>
  <title>Concertino in Blue</title>
  <genre>PROGRESSIVE</genre>
  <bpm>103-155</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>460</notes></normal>
      <hyper><diff>10</diff><notes>915</notes></hyper>
      <another><diff>12</diff><notes>1311</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>486</notes></normal>
      <hyper><diff>10</diff><notes>972</notes></hyper>
      <another><diff>12</diff><notes>1425</notes></another>
    </double>
  </modes>
</song>
<song id="N13011">
  <artist>朱雀</artist>
  <title>CONTRACT</title>
  <genre>SUBLIME TECHNO</genre>
  <bpm>180</bpm>
  <modes>
    <single>
      <normal><diff>8</diff><notes>648</notes></normal>
      <hyper><diff>10</diff><notes>863</notes></hyper>
      <another><diff>11</diff><notes>1056</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>607</notes></normal>
      <hyper><diff>10</diff><notes>856</notes></hyper>
      <another><diff>12</diff><notes>1050</notes></another>
    </double>
  </modes>
</song>
<song id="N13012">
  <artist>Shoichiro Hirata</artist>
  <title>Crazy K.I.N.O.</title>
  <genre>MIXTURE</genre>
  <bpm>145</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>435</notes></normal>
      <hyper><diff>7</diff><notes>596</notes></hyper>
      <another><diff>9</diff><notes>836</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>436</notes></normal>
      <hyper><diff>8</diff><notes>605</notes></hyper>
      <another><diff>11</diff><notes>996</notes></another>
    </double>
  </modes>
</song>
<song id="N13013">
  <artist>DJ MURASAME</artist>
  <title>D.C.fish</title>
  <genre>TECHNO</genre>
  <bpm>155</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>513</notes></normal>
      <hyper><diff>9</diff><notes>998</notes></hyper>
      <another><diff>11</diff><notes>1178</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>505</notes></normal>
      <hyper><diff>8</diff><notes>888</notes></hyper>
      <another><diff>11</diff><notes>1228</notes></another>
    </double>
  </modes>
</song>
<song id="N13014">
  <artist>NAOKI &amp; Tatsh</artist>
  <title>DEEP ROAR</title>
  <genre>SUPER RAVE BEAT</genre>
  <bpm>165</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>503</notes></normal>
      <hyper><diff>7</diff><notes>726</notes></hyper>
      <another><diff>9</diff><notes>976</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>503</notes></normal>
      <hyper><diff>7</diff><notes>721</notes></hyper>
      <another><diff>9</diff><notes>969</notes></another>
    </double>
  </modes>
</song>
<song id="N13015">
  <artist>Tatsh feat. Junko Hirata &amp; Sayaka Minami</artist>
  <title>Double♡♡Loving Heart</title>
  <genre>J-POP</genre>
  <bpm>138</bpm>
  <modes>
    <single>
      <normal><diff>3</diff><notes>292</notes></normal>
      <hyper><diff>6</diff><notes>671</notes></hyper>
      <another><diff>9</diff><notes>909</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>393</notes></normal>
      <hyper><diff>7</diff><notes>730</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13016">
  <artist>Mr.T</artist>
  <title>DUE TOMORROW</title>
  <genre>TECHNO</genre>
  <bpm>100-400</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>470</notes></normal>
      <hyper><diff>9</diff><notes>791</notes></hyper>
      <another><diff>12</diff><notes>1073</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>470</notes></normal>
      <hyper><diff>10</diff><notes>791</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13017">
  <artist>Mr.T plus H</artist>
  <title>Enjoy your life</title>
  <genre>ELECTRONICA</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>348</notes></normal>
      <hyper><diff>6</diff><notes>554</notes></hyper>
      <another><diff>8</diff><notes>738</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>348</notes></normal>
      <hyper><diff>6</diff><notes>554</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13018">
  <artist>K-MASERA</artist>
  <title>EURO-ROMANCE</title>
  <genre>80's TECHNO</genre>
  <bpm>161</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>497</notes></normal>
      <hyper><diff>8</diff><notes>933</notes></hyper>
      <another><diff>10</diff><notes>1056</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>494</notes></normal>
      <hyper><diff>8</diff><notes>893</notes></hyper>
      <another><diff>11</diff><notes>1363</notes></another>
    </double>
  </modes>
</song>
<song id="N13019">
  <artist>玄武</artist>
  <title>Ganymede</title>
  <genre>ESOTERIC SLOWCORE</genre>
  <bpm>72-82</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>571</notes></normal>
      <hyper><diff>10</diff><notes>884</notes></hyper>
      <another><diff>11</diff><notes>1199</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>612</notes></normal>
      <hyper><diff>11</diff><notes>951</notes></hyper>
      <another><diff>12</diff><notes>1363</notes></another>
    </double>
  </modes>
</song>
<song id="N13020">
  <artist>Ryu☆</artist>
  <title>Harmony and Lovely</title>
  <genre>PROGRESSIVE HOUSE</genre>
  <bpm>135</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>457</notes></normal>
      <hyper><diff>8</diff><notes>902</notes></hyper>
      <another><diff>11</diff><notes>1127</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>457</notes></normal>
      <hyper><diff>9</diff><notes>896</notes></hyper>
      <another><diff>11</diff><notes>1122</notes></another>
    </double>
  </modes>
</song>
<song id="N13021">
  <artist>AKIRA YAMAOKA</artist>
  <title>Heavenly Sun (IIDX VERSION)</title>
  <genre>TRANCE</genre>
  <bpm>130</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>421</notes></normal>
      <hyper><diff>7</diff><notes>802</notes></hyper>
      <another><diff>10</diff><notes>1060</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>421</notes></normal>
      <hyper><diff>8</diff><notes>805</notes></hyper>
      <another><diff>10</diff><notes>1060</notes></another>
    </double>
  </modes>
</song>
<song id="N13022">
  <artist>AKIRA YAMAOKA</artist>
  <title>iFUTURELIST</title>
  <genre>FUTURELIST TYPE</genre>
  <bpm>150</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>354</notes></normal>
      <hyper><diff>6</diff><notes>585</notes></hyper>
      <another><diff>8</diff><notes>854</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>352</notes></normal>
      <hyper><diff>6</diff><notes>573</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13023">
  <artist>Caldeira feat. 星野奏子</artist>
  <title>INFERNO</title>
  <genre>BRAZILIAN HOUSE</genre>
  <bpm>135</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>601</notes></normal>
      <hyper><diff>7</diff><notes>828</notes></hyper>
      <another><diff>9</diff><notes>1008</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>600</notes></normal>
      <hyper><diff>7</diff><notes>856</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13024">
  <artist>SEIYA MURAI meets “eimy”</artist>
  <title>Leaving…</title>
  <genre>SYMPHONIC EURO</genre>
  <bpm>145</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>396</notes></normal>
      <hyper><diff>8</diff><notes>714</notes></hyper>
      <another><diff>10</diff><notes>1071</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>386</notes></normal>
      <hyper><diff>7</diff><notes>714</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13025">
  <artist>Sota Fujimori</artist>
  <title>Look To The Sky (cyber True Color)</title>
  <genre>TRANCE</genre>
  <bpm>145</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>505</notes></normal>
      <hyper><diff>8</diff><notes>959</notes></hyper>
      <another><diff>9</diff><notes>1216</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>506</notes></normal>
      <hyper><diff>9</diff><notes>948</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13026">
  <artist>Noria</artist>
  <title>Melody Life</title>
  <genre>NEW ACOUSTIC</genre>
  <bpm>172</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>397</notes></normal>
      <hyper><diff>6</diff><notes>673</notes></hyper>
      <another><diff>9</diff><notes>933</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>399</notes></normal>
      <hyper><diff>6</diff><notes>643</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13027">
  <artist>SLAKE</artist>
  <title>MINT</title>
  <genre>ELECTRONICA</genre>
  <bpm>150</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>524</notes></normal>
      <hyper><diff>10</diff><notes>917</notes></hyper>
      <another><diff>11</diff><notes>1158</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>517</notes></normal>
      <hyper><diff>10</diff><notes>906</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13028">
  <artist>dj TAKA feat. Erika Mochizuki</artist>
  <title>MOON</title>
  <genre>哀愁ユーロ</genre>
  <bpm>156</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>436</notes></normal>
      <hyper><diff>9</diff><notes>1067</notes></hyper>
      <another><diff>10</diff><notes>1118</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>436</notes></normal>
      <hyper><diff>10</diff><notes>1048</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13029">
  <artist>ＴЁЯＲＡ underground</artist>
  <title>Parasite World</title>
  <genre>HYPER J-CORE</genre>
  <bpm>135</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>686</notes></normal>
      <hyper><diff>9</diff><notes>966</notes></hyper>
      <another><diff>10</diff><notes>1194</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>703</notes></normal>
      <hyper><diff>10</diff><notes>985</notes></hyper>
      <another><diff>11</diff><notes>1195</notes></another>
    </double>
  </modes>
</song>
<song id="N13030">
  <artist>kors k feat. PSY</artist>
  <title>Power of Love</title>
  <genre>2 STEP</genre>
  <bpm>135</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>513</notes></normal>
      <hyper><diff>7</diff><notes>848</notes></hyper>
      <another><diff>10</diff><notes>1077</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>512</notes></normal>
      <hyper><diff>8</diff><notes>861</notes></hyper>
      <another><diff>10</diff><notes>1065</notes></another>
    </double>
  </modes>
</song>
<song id="N13031">
  <artist>baby weapon feat. asuka.m</artist>
  <title>Pretty Punisher</title>
  <genre>DANCE POP</genre>
  <bpm>143</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>499</notes></normal>
      <hyper><diff>7</diff><notes>748</notes></hyper>
      <another><diff>10</diff><notes>982</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>499</notes></normal>
      <hyper><diff>7</diff><notes>748</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13033">
  <artist>HHH (Ryu☆ &amp; Dai)</artist>
  <title>So Fabulous !!</title>
  <genre>BUCHIAGE TRANCE</genre>
  <bpm>149</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>556</notes></normal>
      <hyper><diff>8</diff><notes>784</notes></hyper>
      <another><diff>10</diff><notes>1191</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>548</notes></normal>
      <hyper><diff>9</diff><notes>853</notes></hyper>
      <another><diff>11</diff><notes>1214</notes></another>
    </double>
  </modes>
</song>
<song id="N13034">
  <artist>Remixed by DJ YOSHITAKA</artist>
  <title>SPRING RAIN (LLUVIA DE PRIMAVERA)</title>
  <genre>TRANCE</genre>
  <bpm>145</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>494</notes></normal>
      <hyper><diff>7</diff><notes>680</notes></hyper>
      <another><diff>8</diff><notes>905</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>494</notes></normal>
      <hyper><diff>7</diff><notes>670</notes></hyper>
      <another><diff>9</diff><notes>904</notes></another>
    </double>
  </modes>
</song>
<song id="N13035">
  <artist>mh sequence</artist>
  <title>Sun Field</title>
  <genre>HAPPY POP</genre>
  <bpm>152</bpm>
  <modes>
    <single>
      <normal><diff>3</diff><notes>287</notes></normal>
      <hyper><diff>8</diff><notes>777</notes></hyper>
      <another><diff>11</diff><notes>1234</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>449</notes></normal>
      <hyper><diff>9</diff><notes>856</notes></hyper>
      <another><diff>11</diff><notes>1158</notes></another>
    </double>
  </modes>
</song>
<song id="N13036">
  <artist>Tatsh Assault X</artist>
  <title>The Dirty of Loudness</title>
  <genre>SADISTIC HARDCORE</genre>
  <bpm>165</bpm>
  <modes>
    <single>
      <normal><diff>7</diff><notes>740</notes></normal>
      <hyper><diff>10</diff><notes>1154</notes></hyper>
      <another><diff>11</diff><notes>1327</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>723</notes></normal>
      <hyper><diff>10</diff><notes>1122</notes></hyper>
      <another><diff>10</diff><notes>1189</notes></another>
    </double>
  </modes>
</song>
<song id="N13037">
  <artist>D-crew feat. MAKOTO</artist>
  <title>This is Love</title>
  <genre>CORE POP</genre>
  <bpm>175</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>473</notes></normal>
      <hyper><diff>8</diff><notes>910</notes></hyper>
      <another><diff>10</diff><notes>1249</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>489</notes></normal>
      <hyper><diff>8</diff><notes>906</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13038">
  <artist>tiger YAMATO</artist>
  <title>tiger yamato</title>
  <genre>NOISE POP</genre>
  <bpm>150</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>400</notes></normal>
      <hyper><diff>7</diff><notes>712</notes></hyper>
      <another><diff>9</diff><notes>951</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>408</notes></normal>
      <hyper><diff>8</diff><notes>721</notes></hyper>
      <another><diff>10</diff><notes>970</notes></another>
    </double>
  </modes>
</song>
<song id="N13039">
  <artist>dj REMO-CON</artist>
  <title>Tonight?</title>
  <genre>ELECTROCK</genre>
  <bpm>135</bpm>
  <modes>
    <single>
      <normal><diff>3</diff><notes>321</notes></normal>
      <hyper><diff>6</diff><notes>590</notes></hyper>
      <another><diff>8</diff><notes>748</notes></another>
    </single>
    <double>
      <normal><diff>3</diff><notes>321</notes></normal>
      <hyper><diff>7</diff><notes>590</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13040">
  <artist>kors k vs teranoid</artist>
  <title>tripping contact</title>
  <genre>FREEFORM</genre>
  <bpm>182</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>686</notes></normal>
      <hyper><diff>9</diff><notes>989</notes></hyper>
      <another><diff>12</diff><notes>1360</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>725</notes></normal>
      <hyper><diff>10</diff><notes>1081</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13041">
  <artist>kors k vs teranoid</artist>
  <title>tripping contact (teranoid&amp;MC Natsack Remix)</title>
  <genre>GABBA</genre>
  <bpm>187</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>646</notes></normal>
      <hyper><diff>10</diff><notes>1020</notes></hyper>
      <another><diff>11</diff><notes>1258</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>653</notes></normal>
      <hyper><diff>10</diff><notes>968</notes></hyper>
      <another><diff>12</diff><notes>1367</notes></another>
    </double>
  </modes>
</song>
<song id="N13042">
  <artist>L.E.D.</artist>
  <title>TYPE MARS (G-Style Mix)</title>
  <genre>PSYCHEDELIC TRANCE</genre>
  <bpm>159</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>571</notes></normal>
      <hyper><diff>9</diff><notes>974</notes></hyper>
      <another><diff>11</diff><notes>1237</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>576</notes></normal>
      <hyper><diff>10</diff><notes>990</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13043">
  <artist>ELEKTEL</artist>
  <title>Ubiquitous Fantastic Ride</title>
  <genre>ELECTRO LOUNGE</genre>
  <bpm>172</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>325</notes></normal>
      <hyper><diff>7</diff><notes>628</notes></hyper>
      <another><diff>8</diff><notes>835</notes></another>
    </single>
    <double>
      <normal><diff>3</diff><notes>337</notes></normal>
      <hyper><diff>7</diff><notes>615</notes></hyper>
      <another><diff>9</diff><notes>792</notes></another>
    </double>
  </modes>
</song>
<song id="N13044">
  <artist>青龍</artist>
  <title>waxing and wanding</title>
  <genre>DANCE SPEED</genre>
  <bpm>191</bpm>
  <modes>
    <single>
      <normal><diff>7</diff><notes>658</notes></normal>
      <hyper><diff>10</diff><notes>997</notes></hyper>
      <another><diff>11</diff><notes>1457</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>647</notes></normal>
      <hyper><diff>10</diff><notes>966</notes></hyper>
      <another><diff>11</diff><notes>1399</notes></another>
    </double>
  </modes>
</song>
<song id="N13045">
  <artist>jun with TAHIRIH</artist>
  <title>Why did you go away</title>
  <genre>LOVERS EUROBEAT</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>559</notes></normal>
      <hyper><diff>8</diff><notes>904</notes></hyper>
      <another><diff>10</diff><notes>1166</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>552</notes></normal>
      <hyper><diff>9</diff><notes>901</notes></hyper>
      <another><diff>11</diff><notes>1165</notes></another>
    </double>
  </modes>
</song>
<song id="N13046">
  <artist>Sota Fujimori</artist>
  <title>Winning Eleven9 Theme (IIDX EDITION)</title>
  <genre>NU BIGBEAT BREAKS</genre>
  <bpm>140</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>420</notes></normal>
      <hyper><diff>7</diff><notes>730</notes></hyper>
      <another><diff>9</diff><notes>868</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>420</notes></normal>
      <hyper><diff>7</diff><notes>730</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13047">
  <artist>DJ Yoshitaka feat. 杉村ことみ</artist>
  <title>wish</title>
  <genre>CUTE POP'S</genre>
  <bpm>115</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>401</notes></normal>
      <hyper><diff>6</diff><notes>600</notes></hyper>
      <another><diff>8</diff><notes>758</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>400</notes></normal>
      <hyper><diff>7</diff><notes>601</notes></hyper>
      <another><diff>8</diff><notes>784</notes></another>
    </double>
  </modes>
</song>
<song id="N13048">
  <artist>DJ YOSHITAKA feat. 杉村ことみ</artist>
  <title>WISH (EUROBEAT MIX)</title>
  <genre>EUROBEAT</genre>
  <bpm>155</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>532</notes></normal>
      <hyper><diff>8</diff><notes>824</notes></hyper>
      <another><diff>9</diff><notes>990</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>532</notes></normal>
      <hyper><diff>8</diff><notes>793</notes></hyper>
      <another><diff>9</diff><notes>988</notes></another>
    </double>
  </modes>
</song>
<song id="N13049">
  <artist>Sota Fujimori</artist>
  <title>with you…</title>
  <genre>FUNK'N JAZZ HOUSE</genre>
  <bpm>135</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>398</notes></normal>
      <hyper><diff>6</diff><notes>580</notes></hyper>
      <another><diff>9</diff><notes>891</notes></another>
    </single>
    <double>
      <hyper><diff>7</diff><notes>580</notes></hyper>
    </double>
  </modes>
</song>
<song id="N13050">
  <artist>Tatsh</artist>
  <title>Zenius -I- vanisher</title>
  <genre>CYBER OPUS</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>493</notes></normal>
      <hyper><diff>7</diff><notes>790</notes></hyper>
      <another><diff>10</diff><notes>1209</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>492</notes></normal>
      <hyper><diff>8</diff><notes>776</notes></hyper>
      <another><diff>11</diff><notes>1207</notes></another>
    </double>
  </modes>
</song>
<song id="N13051">
  <artist>橙色特別室</artist>
  <title>カゴノトリ～弐式～</title>
  <genre>和式電子音楽</genre>
  <bpm>140</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>581</notes></normal>
      <hyper><diff>9</diff><notes>944</notes></hyper>
      <another><diff>12</diff><notes>1325</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>581</notes></normal>
      <hyper><diff>9</diff><notes>978</notes></hyper>
      <another><diff>12</diff><notes>1586</notes></another>
    </double>
  </modes>
</song>
<song id="N13052">
  <artist>星野奏子 with the BAND</artist>
  <title>タシカナモノ</title>
  <genre>POPROCK</genre>
  <bpm>180</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>472</notes></normal>
      <hyper><diff>7</diff><notes>726</notes></hyper>
      <another><diff>9</diff><notes>1026</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>470</notes></normal>
      <hyper><diff>7</diff><notes>797</notes></hyper>
      <another><diff>10</diff><notes>1191</notes></another>
    </double>
  </modes>
</song>
<song id="N13053">
  <artist>白虎</artist>
  <title>華蝶風雪</title>
  <genre>ASIAN MIXTURE</genre>
  <bpm>199</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>638</notes></normal>
      <hyper><diff>10</diff><notes>1064</notes></hyper>
      <another><diff>11</diff><notes>1500</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>626</notes></normal>
      <hyper><diff>10</diff><notes>1041</notes></hyper>
      <another><diff>12</diff><notes>1481</notes></another>
    </double>
  </modes>
</song>
<song id="N13054">
  <artist>金獅子</artist>
  <title>嘆きの樹</title>
  <genre>CONTEMPORARY</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>8</diff><notes>902</notes></normal>
      <hyper><diff>11</diff><notes>1281</notes></hyper>
      <another><diff>12</diff><notes>2000</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>875</notes></normal>
      <hyper><diff>11</diff><notes>1281</notes></hyper>
      <another><diff>12</diff><notes>2000</notes></another>
    </double>
  </modes>
</song>
<song id="N13055">
  <artist>DJ YOSHITAKA feat. G.S.C license</artist>
  <title>虹色</title>
  <genre>LOVELY TRANS POP</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>488</notes></normal>
      <hyper><diff>8</diff><notes>792</notes></hyper>
      <another><diff>9</diff><notes>934</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>488</notes></normal>
      <hyper><diff>7</diff><notes>793</notes></hyper>
      <another><diff>8</diff><notes>934</notes></another>
    </double>
  </modes>
</song>
<song id="N13056">
  <artist>good-cool</artist>
  <title>罠</title>
  <genre>DRUM'N'ROCK</genre>
  <bpm>180</bpm>
  <modes>
    <single>
      <normal><diff>2</diff><notes>283</notes></normal>
      <hyper><diff>8</diff><notes>777</notes></hyper>
      <another><diff>10</diff><notes>1231</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>374</notes></normal>