<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songlist [
  <!ELEMENT songlist (song, (song|another_song)*)>
  <!ELEMENT song (artist, title, genre, bpm, modes)>
  <!ELEMENT artist (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT genre (#PCDATA)>
  <!ELEMENT bpm (#PCDATA)>
  <!ELEMENT modes (single, double)>
  <!ELEMENT single (normal?, hyper?, another?)>
  <!ELEMENT double (normal?, hyper?, another?)>
  <!ELEMENT normal (diff, notes)>
  <!ELEMENT hyper (diff, notes)>
  <!ELEMENT another (diff, notes)>
  <!ELEMENT diff (#PCDATA)>
  <!ELEMENT notes (#PCDATA)>
  <!ATTLIST song id ID #REQUIRED>
  <!ATTLIST song age (old|new) "new">
  <!ATTLIST song another_id IDREF #IMPLIED>
  <!ELEMENT another_song (artist, title, genre, bpm, modes)>
  <!ATTLIST another_song id ID #REQUIRED>
  <!ATTLIST another_song age (old|new) "new">
  <!ATTLIST another_song original_id IDREF #REQUIRED>
]>
<songlist>
<song id="N12001">
  <artist>Sota Fujimori</artist>
  <title>100% minimoo-G</title>
  <genre>SYNTHETIC PROGRESSIVE ROCK</genre>
  <bpm>252</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>474</notes></normal>
      <hyper><diff>10</diff><notes>871</notes></hyper>
      <another><diff>11</diff><notes>903</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>474</notes></normal>
      <hyper><diff>10</diff><notes>871</notes></hyper>
      <another><diff>11</diff><notes>1414</notes></another>
    </double>
  </modes>
</song>
<song id="N12002">
  <artist>あさき</artist>
  <title>Agnus Dei</title>
  <genre>GOTHIC METAL</genre>
  <bpm>70-168</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>466</notes></normal>
      <hyper><diff>9</diff><notes>850</notes></hyper>
      <another><diff>10</diff><notes>1051</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>465</notes></normal>
      <hyper><diff>8</diff><notes>791</notes></hyper>
      <another><diff>11</diff><notes>1051</notes></another>
    </double>
  </modes>
</song>
<song id="N12003">
  <artist>Twin AmadeuS</artist>
  <title>alla turca con passione</title>
  <genre>NATURAL SOUND</genre>
  <bpm>140</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>409</notes></normal>
      <hyper><diff>8</diff><notes>829</notes></hyper>
      <another><diff>10</diff><notes>1103</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>396</notes></normal>
      <hyper><diff>8</diff><notes>831</notes></hyper>
      <another><diff>9</diff><notes>1057</notes></another>
    </double>
  </modes>
</song>
<song id="N12004">
  <artist>Ryu☆</artist>
  <title>Aurora</title>
  <genre>TRANCE CORE</genre>
  <bpm>181</bpm>
  <modes>
    <single>
      <normal><diff>7</diff><notes>714</notes></normal>
      <hyper><diff>10</diff><notes>1100</notes></hyper>
      <another><diff>11</diff><notes>1280</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>675</notes></normal>
      <hyper><diff>10</diff><notes>1043</notes></hyper>
      <another><diff>12</diff><notes>1218</notes></another>
    </double>
  </modes>
</song>
<song id="N12005">
  <artist>A/I</artist>
  <title>CaptivAte～浄化～</title>
  <genre>NOSTALISH REQUIEM</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>541</notes></normal>
      <hyper><diff>9</diff><notes>946</notes></hyper>
      <another><diff>11</diff><notes>1243</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>540</notes></normal>
      <hyper><diff>9</diff><notes>936</notes></hyper>
      <another><diff>11</diff><notes>1235</notes></another>
    </double>
  </modes>
</song>
<song id="N12006">
  <artist>GINGER</artist>
  <title>キャッシュレスは愛情消すティッシュ</title>
  <genre>K-GROOVE</genre>
  <bpm>117-170</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>409</notes></normal>
      <hyper><diff>8</diff><notes>689</notes></hyper>
      <another><diff>10</diff><notes>1079</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>409</notes></normal>
      <hyper><diff>7</diff><notes>689</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12007">
  <artist>DJ Yoshitaka feat. ERi</artist>
  <title>Catch Me</title>
  <genre>ACID JAZZ</genre>
  <bpm>115</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>405</notes></normal>
      <hyper><diff>8</diff><notes>678</notes></hyper>
      <another><diff>10</diff><notes>925</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>403</notes></normal>
      <hyper><diff>9</diff><notes>685</notes></hyper>
      <another><diff>10</diff><notes>922</notes></another>
    </double>
  </modes>
</song>
<song id="N12008">
  <artist>ウッチーズ</artist>
  <title>Don't let it go</title>
  <genre>J-POP REMIX</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>360</notes></normal>
      <hyper><diff>7</diff><notes>647</notes></hyper>
      <another><diff>9</diff><notes>852</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>360</notes></normal>
      <hyper><diff>6</diff><notes>647</notes></hyper>
      <another><diff>10</diff><notes>852</notes></another>
    </double>
  </modes>
</song>
<song id="N12009">
  <artist>414</artist>
  <title>double thrash</title>
  <genre>BATTLE2005</genre>
  <bpm>166</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>527</notes></normal>
      <hyper><diff>10</diff><notes>1066</notes></hyper>
      <another><diff>10</diff><notes>1206</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>527</notes></normal>
      <hyper><diff>10</diff><notes>1048</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12010">
  <artist>TЁЯRA</artist>
  <title>EDEN</title>
  <genre>HYPER J-POP SIX</genre>
  <bpm>200</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>660</notes></normal>
      <hyper><diff>9</diff><notes>969</notes></hyper>
      <another><diff>10</diff><notes>1363</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>640</notes></normal>
      <hyper><diff>8</diff><notes>733</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12011">
  <artist>AKIRA YAMAOKA</artist>
  <title>EMPTY OF THE SKY</title>
  <genre>E-ROCK</genre>
  <bpm>182</bpm>
  <modes>
    <single>
      <normal><diff>3</diff><notes>334</notes></normal>
      <hyper><diff>5</diff><notes>526</notes></hyper>
      <another><diff>8</diff><notes>843</notes></another>
    </single>
    <double>
      <normal><diff>3</diff><notes>334</notes></normal>
      <hyper><diff>5</diff><notes>526</notes></hyper>
      <another><diff>8</diff><notes>842</notes></another>
    </double>
  </modes>
</song>
<song id="N12012">
  <artist>good-cool</artist>
  <title>First Resolution</title>
  <genre>TECHNO RAVE</genre>
  <bpm>150</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>421</notes></normal>
      <hyper><diff>7</diff><notes>808</notes></hyper>
      <another><diff>9</diff><notes>1077</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>421</notes></normal>
      <hyper><diff>8</diff><notes>819</notes></hyper>
      <another><diff>10</diff><notes>1077</notes></another>
    </double>
  </modes>
</song>
<song id="N12013">
  <artist>ULTRAdoof</artist>
  <title>FUNKTION</title>
  <genre>CYBER FUNK</genre>
  <bpm>133</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>489</notes></normal>
      <hyper><diff>7</diff><notes>840</notes></hyper>
      <another><diff>9</diff><notes>1040</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>511</notes></normal>
      <hyper><diff>7</diff><notes>797</notes></hyper>
      <another><diff>9</diff><notes>927</notes></another>
    </double>
  </modes>
</song>
<song id="N12014">
  <artist>青野りえ</artist>
  <title>garden</title>
  <genre>SWING WALTZ</genre>
  <bpm>220</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>440</notes></normal>
      <hyper><diff>7</diff><notes>773</notes></hyper>
      <another><diff>10</diff><notes>1100</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>461</notes></normal>
      <hyper><diff>7</diff><notes>774</notes></hyper>
      <another><diff>12</diff><notes>1396</notes></another>
    </double>
  </modes>
</song>
<song id="N12015">
  <artist>Tatsh feat. 星野奏子</artist>
  <title>月光</title>
  <genre>J-EUROBEAT</genre>
  <bpm>155</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>455</notes></normal>
      <hyper><diff>8</diff><notes>900</notes></hyper>
      <another><diff>10</diff><notes>1246</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>440</notes></normal>
      <hyper><diff>9</diff><notes>922</notes></hyper>
      <another><diff>10</diff><notes>1175</notes></another>
    </double>
  </modes>
</song>
<song id="N12016">
  <artist>Disconation</artist>
  <title>Get'em up to R.A.V.E</title>
  <genre>RAVE</genre>
  <bpm>145</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>599</notes></normal>
      <hyper><diff>8</diff><notes>892</notes></hyper>
      <another><diff>10</diff><notes>1158</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>595</notes></normal>
      <hyper><diff>8</diff><notes>890</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12017">
  <artist>SLAKE</artist>
  <title>GREEN EYES</title>
  <genre>BROKEN TEK</genre>
  <bpm>170</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>507</notes></normal>
      <hyper><diff>8</diff><notes>827</notes></hyper>
      <another><diff>10</diff><notes>1123</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>494</notes></normal>
      <hyper><diff>9</diff><notes>828</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12018">
  <artist>jun with TAHIRIH</artist>
  <title>HAPPY☆ANGEL</title>
  <genre>HAPPY HARDCORE</genre>
  <bpm>180</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>555</notes></normal>
      <hyper><diff>7</diff><notes>782</notes></hyper>
      <another><diff>10</diff><notes>1052</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>555</notes></normal>
      <hyper><diff>7</diff><notes>776</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12019">
  <artist>小坂りゆ</artist>
  <title>ヒマワリ</title>
  <genre>J-HAPPY HARDCORE</genre>
  <bpm>185</bpm>
  <modes>
    <single>
      <normal><diff>3</diff><notes>280</notes></normal>
      <hyper><diff>9</diff><notes>947</notes></hyper>
      <another><diff>10</diff><notes>1042</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>396</notes></normal>
      <hyper><diff>8</diff><notes>852</notes></hyper>
      <another><diff>9</diff><notes>943</notes></another>
    </double>
  </modes>
</song>
<song id="N12020">
  <artist>有沢みはる from BeForU</artist>
  <title>I am</title>
  <genre>CYBER J-ROCK</genre>
  <bpm>190</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>555</notes></normal>
      <hyper><diff>8</diff><notes>883</notes></hyper>
      <another><diff>10</diff><notes>1096</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>611</notes></normal>
      <hyper><diff>8</diff><notes>883</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12021">
  <artist>Ryu☆</artist>
  <title>in motion</title>
  <genre>CLICK HOUSE</genre>
  <bpm>138</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>432</notes></normal>
      <hyper><diff>6</diff><notes>545</notes></hyper>
      <another><diff>7</diff><notes>661</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>432</notes></normal>
      <hyper><diff>6</diff><notes>545</notes></hyper>
      <another><diff>8</diff><notes>661</notes></another>
    </double>
  </modes>
</song>
<song id="N12022">
  <artist>dj TAKA</artist>
  <title>INAZUMA</title>
  <genre>TRANCE</genre>
  <bpm>148</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>561</notes></normal>
      <hyper><diff>9</diff><notes>930</notes></hyper>
      <another><diff>11</diff><notes>1368</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>584</notes></normal>
      <hyper><diff>9</diff><notes>917</notes></hyper>
      <another><diff>12</diff><notes>1554</notes></another>
    </double>
  </modes>
</song>
<song id="N12023">
  <artist>Risk Junk feat. Erika Mochizuki</artist>
  <title>LESSON 5</title>
  <genre>HAPPY EXTREME</genre>
  <bpm>152</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>654</notes></normal>
      <hyper><diff>8</diff><notes>949</notes></hyper>
      <another><diff>9</diff><notes>1261</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>542</notes></normal>
      <hyper><diff>7</diff><notes>939</notes></hyper>
      <another><diff>11</diff><notes>1471</notes></another>
    </double>
  </modes>
</song>
<song id="N12024">
  <artist>Mitsuto Suzuki</artist>
  <title>Listen up</title>
  <genre>CLICK HOUSE</genre>
  <bpm>133</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>501</notes></normal>
      <hyper><diff>7</diff><notes>742</notes></hyper>
      <another><diff>9</diff><notes>1051</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>501</notes></normal>
      <hyper><diff>8</diff><notes>814</notes></hyper>
      <another><diff>10</diff><notes>1049</notes></another>
    </double>
  </modes>
</song>
<song id="N12025">
  <artist>SHRINE 418</artist>
  <title>Little Little Princess</title>
  <genre>PUNK OPERA</genre>
  <bpm>180-212</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>558</notes></normal>
      <hyper><diff>10</diff><notes>1118</notes></hyper>
      <another><diff>11</diff><notes>1420</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>560</notes></normal>
      <hyper><diff>10</diff><notes>1171</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12026">
  <artist>D.J.SWAN</artist>
  <title>Love Magic</title>
  <genre>DRUM'N'BASS</genre>
  <bpm>170</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>515</notes></normal>
      <hyper><diff>8</diff><notes>895</notes></hyper>
      <another><diff>10</diff><notes>991</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>515</notes></normal>
      <hyper><diff>8</diff><notes>895</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12027">
  <artist>Amuro vs Killer</artist>
  <title>冥</title>
  <genre>HUMAN SEQUENCER</genre>
  <bpm>66-200</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>555</notes></normal>
      <hyper><diff>10</diff><notes>1111</notes></hyper>
      <another><diff>12</diff><notes>2000</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>555</notes></normal>
      <hyper><diff>11</diff><notes>1104</notes></hyper>
      <another><diff>12</diff><notes>2000</notes></another>
    </double>
  </modes>
</song>
<song id="N12028">
  <artist>Osamu Kubota</artist>
  <title>mind the gap</title>
  <genre>UK PROGRESSIVE</genre>
  <bpm>98-147</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>395</notes></normal>
      <hyper><diff>7</diff><notes>550</notes></hyper>
      <another><diff>9</diff><notes>840</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>380</notes></normal>
      <hyper><diff>8</diff><notes>550</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12029">
  <artist>ELEKTEL</artist>
  <title>MOON RACE</title>
  <genre>FUTURE HOUSE</genre>
  <bpm>147</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>434</notes></normal>
      <hyper><diff>7</diff><notes>598</notes></hyper>
      <another><diff>9</diff><notes>957</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>433</notes></normal>
      <hyper><diff>10</diff><notes>598</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12030">
  <artist>DANCE☆MAN</artist>
  <title>オレはビートマニア！お前は何マニア？</title>
  <genre>FUNK</genre>
  <bpm>123</bpm>
  <modes>
    <single>
      <normal><diff>7</diff><notes>414</notes></normal>
      <hyper><diff>8</diff><notes>763</notes></hyper>
      <another><diff>10</diff><notes>873</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>414</notes></normal>
      <hyper><diff>8</diff><notes>752</notes></hyper>
      <another><diff>9</diff><notes>789</notes></another>
    </double>
  </modes>
</song>
<song id="N12031">
  <artist>kobo</artist>
  <title>PATRIOTISM</title>
  <genre>DRUM'N'BASS</genre>
  <bpm>180</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>390</notes></normal>
      <hyper><diff>7</diff><notes>679</notes></hyper>
      <another><diff>9</diff><notes>929</notes></another>
    </single>
    <double>
      <normal><diff>3</diff><notes>386</notes></normal>
      <hyper><diff>7</diff><notes>679</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12032">
  <artist>Kiyommy+Seiya</artist>
  <title>Pink Rose</title>
  <genre>HEART</genre>
  <bpm>116-146</bpm>
  <modes>
    <single>
      <normal><diff>3</diff><notes>297</notes></normal>
      <hyper><diff>5</diff><notes>486</notes></hyper>
      <another><diff>6</diff><notes>525</notes></another>
    </single>
    <double>
      <normal><diff>3</diff><notes>297</notes></normal>
      <hyper><diff>5</diff><notes>486</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12033">
  <artist>Sota Fujimori</artist>
  <title>PLASMA</title>
  <genre>SYNTHESIZED TECHNO</genre>
  <bpm>148</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>479</notes></normal>
      <hyper><diff>8</diff><notes>848</notes></hyper>
      <another><diff>9</diff><notes>1145</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>479</notes></normal>
      <hyper><diff>8</diff><notes>848</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12034">
  <artist>dj REMO-CON</artist>
  <title>Pollinosis</title>
  <genre>HARD DANCE</genre>
  <bpm>145</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>405</notes></normal>
      <hyper><diff>6</diff><notes>590</notes></hyper>
      <another><diff>11</diff><notes>1278</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>464</notes></normal>
      <hyper><diff>8</diff><notes>644</notes></hyper>
      <another><diff>9</diff><notes>829</notes></another>
    </double>
  </modes>
</song>
<song id="N12035">
  <artist>Y&amp;Co.</artist>
  <title>POODLE</title>
  <genre>EUROBEAT</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>492</notes></normal>
      <hyper><diff>8</diff><notes>956</notes></hyper>
      <another><diff>10</diff><notes>1156</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>493</notes></normal>
      <hyper><diff>8</diff><notes>880</notes></hyper>
      <another><diff>11</diff><notes>1438</notes></another>
    </double>
  </modes>
</song>
<song id="N12036">
  <artist>dj TAKA feat. Gt.Shintaro</artist>
  <title>rage against usual</title>
  <genre>DIGI-ROCK</genre>
  <bpm>152</bpm>
  <modes>
    <single>
      <normal><diff>7</diff><notes>697</notes></normal>
      <hyper><diff>10</diff><notes>1060</notes></hyper>
      <another><diff>12</diff><notes>1527</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>697</notes></normal>
      <hyper><diff>10</diff><notes>1081</notes></hyper>
      <another><diff>11</diff><notes>1215</notes></another>
    </double>
  </modes>
</song>
<song id="N12037">
  <artist>Chonan Chiharu</artist>
  <title>ラクエン</title>
  <genre>REGGAE</genre>
  <bpm>99-198</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>369</notes></normal>
      <hyper><diff>6</diff><notes>498</notes></hyper>
      <another><diff>11</diff><notes>1034</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>368</notes></normal>
      <hyper><diff>9</diff><notes>723</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12038">
  <artist>CALF</artist>
  <title>SCREAM SQUAD</title>
  <genre>BREAKCORE</genre>
  <bpm>220</bpm>
  <modes>
    <single>
      <normal><diff>7</diff><notes>609</notes></normal>
      <hyper><diff>10</diff><notes>869</notes></hyper>
      <another><diff>12</diff><notes>1073</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>579</notes></normal>
      <hyper><diff>10</diff><notes>863</notes></hyper>
      <another><diff>12</diff><notes>1072</notes></another>
    </double>
  </modes>
</song>
<song id="N12039">
  <artist>DJ MURASAME</artist>
  <title>Scripted Connection⇒ long mix</title>
  <genre>TECHNO</genre>
  <bpm>151</bpm>
  <modes>
    <single>
      <hyper><diff>-</diff><notes>4459</notes></hyper>
    </single>
    <double>
    </double>
  </modes>
</song>
<song id="N12040">
  <artist>MATALLY</artist>
  <title>SEXYSEXYCHEVY</title>
  <genre>BIG BEAT</genre>
  <bpm>140</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>418</notes></normal>
      <hyper><diff>6</diff><notes>582</notes></hyper>
      <another><diff>8</diff><notes>913</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>418</notes></normal>
      <hyper><diff>7</diff><notes>689</notes></hyper>
      <another><diff>9</diff><notes>913</notes></another>
    </double>
  </modes>
</song>
<song id="N12041">
  <artist>kors k</artist>
  <title>SigSig</title>
  <genre>MAKINA</genre>
  <bpm>179</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>548</notes></normal>
      <hyper><diff>7</diff><notes>864</notes></hyper>
      <another><diff>10</diff><notes>1309</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>552</notes></normal>
      <hyper><diff>7</diff><notes>884</notes></hyper>
      <another><diff>11</diff><notes>1259</notes></another>
    </double>
  </modes>
</song>
<song id="N12042">
  <artist>SILVER FOX PRODUCTIONS feat. 星野奏子</artist>
  <title>SPARK !</title>
  <genre>DANCE POP</genre>
  <bpm>126</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>355</notes></normal>
      <hyper><diff>7</diff><notes>681</notes></hyper>
      <another><diff>9</diff><notes>814</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>355</notes></normal>
      <hyper><diff>6</diff><notes>679</notes></hyper>
      <another><diff>8</diff><notes>825</notes></another>
    </double>
  </modes>
</song>
<song id="N12043">
  <artist>AKIRA YAMAOKA</artist>
  <title>tant pis pour toi</title>
  <genre>TECHNO</genre>
  <bpm>138</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>385</notes></normal>
      <hyper><diff>8</diff><notes>676</notes></hyper>
      <another><diff>10</diff><notes>862</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>385</notes></normal>
      <hyper><diff>9</diff><notes>676</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12044">
  <artist>L.E.D./Remixed by Ryu☆</artist>
  <title>合体せよ！ストロングイェーガー！！ (Ryu☆remix)</title>
  <genre>HARD DANCE</genre>
  <bpm>155</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>564</notes></normal>
      <hyper><diff>8</diff><notes>807</notes></hyper>
      <another><diff>11</diff><notes>972</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>556</notes></normal>
      <hyper><diff>9</diff><notes>784</notes></hyper>
      <another><diff>11</diff><notes>935</notes></another>
    </double>
  </modes>
</song>
<song id="N12045">
  <artist>TOMOSUKE</artist>
  <title>Tizona d'El Cid</title>
  <genre>MPB</genre>
  <bpm>265</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>495</notes></normal>
      <hyper><diff>9</diff><notes>1000</notes></hyper>
      <another><diff>10</diff><notes>1178</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>491</notes></normal>
      <hyper><diff>10</diff><notes>1000</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12046">
  <artist>BIG IDEA</artist>
  <title>TOE JAM</title>
  <genre>COUNTRY TECHNO</genre>
  <bpm>90-160</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>393</notes></normal>
      <hyper><diff>8</diff><notes>704</notes></hyper>
      <another><diff>8</diff><notes>717</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>393</notes></normal>
      <hyper><diff>8</diff><notes>704</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12047">
  <artist>Tatsh&amp;DAYBREAKERS NEXT</artist>
  <title>Twelfth Style</title>
  <genre>HAPPY EURO PARADISE</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>6</diff><notes>630</notes></normal>
      <hyper><diff>7</diff><notes>778</notes></hyper>
      <another><diff>10</diff><notes>1033</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>707</notes></normal>
      <hyper><diff>9</diff><notes>976</notes></hyper>
      <another><diff>10</diff><notes>1070</notes></another>
    </double>
  </modes>
</song>
<song id="N12048">
  <artist>南さやか(BeForU) with platoniX</artist>
  <title>Under the Sky</title>
  <genre>J-EUROTRANCE</genre>
  <bpm>170</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>458</notes></normal>
      <hyper><diff>7</diff><notes>710</notes></hyper>
      <another><diff>9</diff><notes>875</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>390</notes></normal>
      <hyper><diff>7</diff><notes>670</notes></hyper>
      <another><diff>9</diff><notes>830</notes></another>
    </double>
  </modes>
</song>
<song id="N12049">
  <artist>Mr.T</artist>
  <title>vault of heaven</title>
  <genre>ELECTROSHOCK</genre>
  <bpm>160</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>401</notes></normal>
      <hyper><diff>8</diff><notes>728</notes></hyper>
      <another><diff>10</diff><notes>1010</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>401</notes></normal>
      <hyper><diff>7</diff><notes>728</notes></hyper>
      <another><diff>9</diff><notes>1020</notes></another>
    </double>
  </modes>
</song>
<song id="N12050">
  <artist>iconoclasm</artist>
  <title>Votum stellarum</title>
  <genre>ANTHEM TRANCE</genre>
  <bpm>136-147</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>413</notes></normal>
      <hyper><diff>9</diff><notes>857</notes></hyper>
      <another><diff>10</diff><notes>1017</notes></another>
    </single>
    <double>
      <normal><diff>4</diff><notes>413</notes></normal>
      <hyper><diff>11</diff><notes>965</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12051">
  <artist>DANCE☆MAN feat. Disっ娘</artist>
  <title>We are Disっ娘よっつ打ち命</title>
  <genre>DISCO</genre>
  <bpm>129</bpm>
  <modes>
    <single>
      <normal><diff>3</diff><notes>336</notes></normal>
      <hyper><diff>5</diff><notes>490</notes></hyper>
      <another><diff>9</diff><notes>837</notes></another>
    </single>
    <double>
      <normal><diff>3</diff><notes>336</notes></normal>
      <hyper><diff>5</diff><notes>490</notes></hyper>
      <another><diff>9</diff><notes>873</notes></another>
    </double>
  </modes>
</song>
<song id="N12052">
  <artist>Tatsh</artist>
  <title>Xepher</title>
  <genre>MEDIEVAL CHOIR</genre>
  <bpm>170</bpm>
  <modes>
    <single>
      <normal><diff>5</diff><notes>571</notes></normal>
      <hyper><diff>10</diff><notes>1135</notes></hyper>
      <another><diff>11</diff><notes>1520</notes></another>
    </single>
    <double>
      <normal><diff>5</diff><notes>559</notes></normal>
      <hyper><diff>10</diff><notes>1089</notes></hyper>
      <another><diff>11</diff><notes>1498</notes></another>
    </double>
  </modes>
</song>
<song id="N12053" age="old">
  <artist>dj nagureo</artist>
  <title>5.1.1.</title>
  <genre>IANO AMBIENT</genre>
  <bpm>101</bpm>
  <modes>
    <single>
      <normal><diff>1</diff><notes>99</notes></normal>
      <hyper><diff>6</diff><notes>511</notes></hyper>
      <another><diff>10</diff><notes>786</notes></another>
    </single>
    <double>
      <normal><diff>1</diff><notes>99</notes></normal>
      <hyper><diff>6</diff><notes>511</notes></hyper>
      <another><diff>10</diff><notes>796</notes></another>
    </double>
  </modes>
</song>
<song id="N12054" age="old">
  <artist>baby weapon feat. Asuka.M</artist>
  <title>Dr.LOVE</title>
  <genre>DANCE POP</genre>
  <bpm>123</bpm>
  <modes>
    <single>
      <normal><diff>2</diff><notes>204</notes></normal>
      <hyper><diff>3</diff><notes>261</notes></hyper>
      <another><diff>3</diff><notes>290</notes></another>
    </single>
    <double>
      <normal><diff>3</diff><notes>259</notes></normal>
      <hyper><diff>4</diff><notes>321</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12055" age="old">
  <artist>TaQ</artist>
  <title>Electro Tuned (the SubS mix)</title>
  <genre>BIG BEAT</genre>
  <bpm>125</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>390</notes></normal>
      <hyper><diff>5</diff><notes>483</notes></hyper>
      <another><diff>6</diff><notes>537</notes></another>
    </single>
    <double>
      <normal><diff>6</diff><notes>469</notes></normal>
      <hyper><diff>8</diff><notes>569</notes></hyper>
    </double>
  </modes>
</song>
<song id="N12056" age="old">
  <artist>TaQ</artist>
  <title>Holic</title>
  <genre>HARD TECHNO</genre>
  <bpm>155</bpm>
  <modes>
    <single>
      <normal><diff>4</diff><notes>395</notes></normal>
      <hyper><diff>7</diff><notes>624</notes></hyper>
      <another><diff>11</diff><notes>880</notes></another>
    </single>
    <double>
      <normal><diff>7</diff><notes>680</notes></normal>